# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#00_about"
  weight = 1

[[main]]
  name = "Experience"
  url = "#02_experience"
  weight = 2

[[main]]
  name = "Projects"
  url = "project/"
  weight = 3

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 4

[[main]]
  name = "Talks"
  url = "talk/"
  weight = 5

[[main]]
  name = "Hobbies"
  url = "#06_hobbies"
  weight = 6

[[main]]
  name = "Posts"
  url = "post/"
  weight = 7

[[main]]
  name = "Contact"
  url = "#99_contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
